#### Consider the below code to answer further questions:
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.



Answer :  Yes, there is a difference in the data type of variables list_ and array_list. The list_ variable is a Python list object, whereas the array_list variable is a Numpy array object.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
list_ = ['1', '2', '3', '4', '5']

for i in list_:
    print(type(i))

array_list = np.array(object=list_)
for i in array_list:
    print(i.dtype)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


## Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.



Answer : Yes, there will be a difference in the data type of the elements present in list_ and array_list when array_list is created with the dtype parameter set to int. The list_ variable contains strings, whereas array_list will be an array of integers.

In [3]:
list_ = ['1', '2', '3', '4', '5']

for i in list_:
    print(type(i))
    
array_list = np.array(object=list_, dtype=int)

for i in array_list:
    print(type(i))    


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)



## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [4]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

arr = np.zeros((3, 3))

print(arr)
print(arr.size)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


## Q6. Create an identity matrix of shape (5,5) using numpy functions?

## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
import numpy as np

arr1 = np.identity(5)

print(arr1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
